(require 'package)
(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/"))
(package-initialize)

(setq url-http-attempt-keepalives nil)

(defvar my-packages
  '(auto-complete clojure-mode fuzzy geiser highlight idomenu markdown-mode mic-paren
		  nrepl paredit popup rainbow-delimiters rainbow-mode undo-tree magit ac-nrepl rinari)
  "A list of packages to ensure are installed at launch.")

(mapc
 (lambda (package)
   (or (package-installed-p package)
       (if (y-or-n-p (format "Package %s is missing. Install it? " package)) 
           (package-install package))))
 my-packages)

(provide 'my-packages)

;;utf-8 mode default
(setq locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

;;whitespace and 80 line highlight
 (require 'whitespace)
 (setq whitespace-style '(face empty tabs lines-tail trailing))
 (global-whitespace-mode t)

;; Files to load
(load-file "~/.emacs.d/elisp/displat-windows.el")

;; General Settings
(set-default-font "SourceCodePro 12")
(add-to-list 'load-path "~/.emacs.d/elisp/")
(setq linum-format "%3d")
(global-linum-mode t)
(setq inhibit-splash-screen t)
(tool-bar-mode -1)
(setq visible-bell t)

(setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
(setq auto-save-file-name-transforms
      `((".*" ,temporary-file-directory t)))


;; Save all tempfiles in $TMPDIR/emacs$UID/                                                        
(defconst emacs-tmp-dir (format "%s/%s%s/" temporary-file-directory "emacs" (user-uid)))
(setq backup-directory-alist
      `((".*" . ,emacs-tmp-dir)))
(setq auto-save-file-name-transforms
      `((".*" ,emacs-tmp-dir t)))
(setq auto-save-list-file-prefix
      emacs-tmp-dir)

;; Clojure Stuff
(add-hook 'nrepl-interaction-mode-hook
  'nrepl-turn-on-eldoc-mode)
(require 'mic-paren)
(paren-activate)

;; Chuck stuff
(require 'chuck-mode)

;; Highlight expression on eval
(require 'easymenu)
(require 'nrepl-eval-sexp-fu)
(require 'highlight)
(turn-on-nrepl-eval-sexp-fu-flash-mode)
(setq nrepl-eval-sexp-fu-flash-duration 0.5)

(require 'rainbow-delimiters)

(load-file "~/.emacs.d/conf/auto-complete-conf.el")
(load-file "~/.emacs.d/conf/nrepl-conf.el")
(load-file "~/.emacs.d/conf/paredit-conf.el")
(load-file "~/.emacs.d/conf/clojure-conf.el")

;; Theme Stuff
(add-to-list 'custom-theme-load-path "/home/jason/.emacs.d/themes/")
(load-theme 'displat-zenburn t)

;;bindings
(load-file "~/.emacs.d/lib/bindings.el")

;;ruby  stuff
(defun set-newline-and-indent ()
    (local-set-key (kbd "RET") 'newline-and-indent))
(add-hook 'lisp-mode-hook 'set-newline-and-indent)

;;change to ruby 2
(add-to-list 'load-path "~/.emacs.d/elisp/chruby.el")
(require 'rvm)
(rvm-use-default)

(add-to-list 'load-path "~/.emacs.d/elisp/ruby-dev.el")
(autoload 'turn-on-ruby-dev "ruby-dev" nil t)
(add-hook 'ruby-mode-hook 'turn-on-ruby-dev)
(add-hook 'ruby-mode-hook 'robe-mode)

(add-to-list 'load-path "~/.emacs.d/elisp/enhanced-ruby-mode") ; must be added after any path containing old ruby-mode
(autoload 'enh-ruby-mode "enh-ruby-mode" "Major mode for ruby files" t)
(add-to-list 'auto-mode-alist '("\\.rb$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("Guardfile" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("\\.gemspec" . enh-ruby-mode))
(add-to-list 'interpreter-mode-alist '("ruby" . enh-ruby-mode))

;;use pry for inf-ruby
(load-file "~/.emacs.d/elisp/inf-ruby-settings.el")
;;resense
(setq rsense-home "/opt/rsense-0.3")
(add-to-list 'load-path (concat rsense-home "/etc"))
(require 'rsense)

(require 'smartparens-config)
(require 'smartparens-ruby)
(smartparens-global-mode)
(show-smartparens-global-mode t)
(sp-with-modes '(rhtml-mode)
  (sp-local-pair "<" ">")
  (sp-local-pair "<%" "%>"))
;;auto-generated by package
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector ["#3A3A3A" "#CC9393" "#7F9F7F" "#F0DFAF" "#8CD0D3" "#DC8CC3" "#93E0E3" "#DCDCCC"])
 '(custom-safe-themes (quote ("541b58826d3d7abe525a8a4c88046e0a4c81a753b1b94ce4a1020e5f2eef15a2" default)))
 '(fci-rule-color "#383838")
 '(vc-annotate-background "#2B2B2B")
 '(vc-annotate-color-map (quote ((20 . "#BC8383") (40 . "#CC9393") (60 . "#DFAF8F") (80 . "#D0BF8F") (100 . "#E0CF9F") (120 . "#F0DFAF") (140 . "#7F9F7F") (160 . "#7F9F7F") (180 . "#8FB28F") (200 . "#9FC59F") (220 . "#AFD8AF") (240 . "#BFEBBF") (260 . "#93E0E3") (280 . "#6CA0A3") (300 . "#7CB8BB") (320 . "#8CD0D3") (340 . "#94BFF3") (360 . "#DC8CC3"))))
 '(vc-annotate-very-old-color "#DC8CC3"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;;ansi-term (with thanks to
;;http://www.enigmacurry.com/2008/12/26/emacs-ansi-term-tricks/)
(require 'term)
(defun visit-ansi-term ()
  "If the current buffer is:
     1) a running ansi-term named *ansi-term*, rename it.
     2) a stopped ansi-term, kill it and create a new one.
     3) a non ansi-term, go to an already running ansi-term
        or start a new one while killing a defunt one"
  (interactive)
  (let ((is-term (string= "term-mode" major-mode))
        (is-running (term-check-proc (buffer-name)))
        (term-cmd "/bin/bash")
        (anon-term (get-buffer "*ansi-term*")))
    (if is-term
        (if is-running
            (if (string= "*ansi-term*" (buffer-name))
                (call-interactively 'rename-buffer)
              (if anon-term
                  (switch-to-buffer "*ansi-term*")
                (ansi-term term-cmd)))
          (kill-buffer (buffer-name))
          (ansi-term term-cmd))
      (if anon-term
          (if (term-check-proc "*ansi-term*")
              (switch-to-buffer "*ansi-term*")
            (kill-buffer "*ansi-term*")
            (ansi-term term-cmd))
        (ansi-term term-cmd)))))
(global-set-key (kbd "<f2>") 'visit-ansi-term)
(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)
